# Generated by Django 5.1.2 on 2024-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('courier_delivery', models.TextField(blank=True, verbose_name='Курьером по Соль-Илецку')),
                ('delivery_in_russia', models.TextField(blank=True, verbose_name='Доставка по России')),
                ('cash_payment', models.TextField(blank=True, verbose_name='Наличными')),
                ('cash_on_delivery', models.TextField(blank=True, verbose_name='Наложенным платежом')),
                ('electronic_money', models.TextField(blank=True, verbose_name='Электронными деньгами')),
                ('address', models.TextField(blank=True, verbose_name='Наш адрес')),
                ('manager_phone', models.TextField(blank=True, max_length=15, verbose_name='Телефон отдела продаж ')),
                ('timetable', models.TextField(blank=True, verbose_name='График работы отдела продаж')),
                ('mail', models.TextField(blank=True, verbose_name='Электронный ящик')),
            ],
            options={
                'verbose_name': 'Контактную информацию',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
    ]
